# -*- coding: utf-8 -*-
"""COPIAAAAA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16TAWfqXBE4UP4LSsxIQ05MZrqAdBnbuC
"""

#conectar google colab con los archivos
from google.colab import files
import pandas as pd

#subir la base de datos en archivo excel
print("📂 Subir Base de Datos\n")

uploaded = files.upload()

base_excel = list(uploaded.keys())[0]

#leer la base de datos
df = pd.read_excel(base_excel)

#establecer las columnas
columnas_requeridas = [
    "nivel",
    "categoría",
    "mito",
    "A",
    "B",
    "C",
    "D",
    "respuesta",
    "explicación"
]

for columna in columnas_requeridas:
    if columna not in df.columns:
        print(f"❌ Falta la columna '{columna}' en el Excel.")
        raise SystemExit

#colocar el título del juego
print("\n🩺💜 Trivia: ¿Mito o realidad sobre el SOMP?")
print("Pon a prueba tus conocimientos y combate la desinformación.")

#organizar la selección de niveles
orden_niveles = ["Fácil", "Medio", "Difícil"]

niveles = [
    nivel for nivel in orden_niveles
    if nivel in df["nivel"].unique()
]

print("\n📚 Niveles disponibles:\n")

for i, nivel in enumerate(niveles, start=1):
    print(f"{i}. {nivel}")

while True:
    try:
        opcion = int(input("\nElige un nivel (número): "))

        if 1 <= opcion <= len(niveles):
            nivel_elegido = niveles[opcion - 1]
            break

        print("❌ Número fuera de rango.")

    except ValueError:
        print("❌ Debes ingresar un número.")

print(f"\n✅ Nivel seleccionado: {nivel_elegido}")

#filtrar las preguntas correspondientes al nivel elegido
preguntas_nivel = df[df["nivel"] == nivel_elegido]

if len(preguntas_nivel) == 0:
    print("❌ No existen preguntas para ese nivel.")
    raise SystemExit

#seleccionar 10 preguntas aleatoriamente
cantidad_preguntas = min(10, len(preguntas_nivel))

preguntas = preguntas_nivel.sample(
    n=cantidad_preguntas,
    random_state=None
)

puntaje = 0

#inicio del juego
for numero, (_, fila) in enumerate(
    preguntas.iterrows(),
    start=1
):

    print(f"📖 Pregunta {numero} de {cantidad_preguntas}")
    print(f"📂 Categoría: {fila['categoría']}")

    print("\n🔷 MITO")
    print(f"{fila['mito']}")

    print(f"\nA) {fila['A']}")
    print(f"B) {fila['B']}")
    print(f"C) {fila['C']}")
    print(f"D) {fila['D']}")

    while True:

        respuesta = input(
            "\nTu respuesta (A/B/C/D): "
        ).strip().upper()

        if respuesta in ["A", "B", "C", "D"]:
            break

        print("‼️ Solo puedes responder A, B, C o D.")

    correcta = str(fila["respuesta"]).strip().upper()

    if respuesta == correcta:
        print("\n✅ ¡Correcto!")
        puntaje += 1
    else:
        print("\n❌ Incorrecto")
        print(f"Respuesta correcta: {correcta}")

    print(f"💡 Información:")
    print(fila["explicación"])
    print()

#resultados conseguidos
porcentaje = (puntaje / cantidad_preguntas) * 100

print("🏁 FIN DEL JUEGO")

print(f"\n➡️ Puntaje: {puntaje}/{cantidad_preguntas}")

if porcentaje == 100:
    print("🏆 ¡Excelente! Conoces muy bien el SOMP.")
elif porcentaje >= 80:
    print("🌟 Muy buen trabajo. Tienes conocimientos sólidos sobre el SOMP.")
elif porcentaje >= 60:
    print("👏 Vas por buen camino. Sigue aprendiendo sobre el SOMP.")
elif porcentaje >= 40:
    print("👀 Aún existen algunos mitos por aclarar.")
else:
    print("📖 Sigue informándote sobre el SOMP y ayuda a combatir la desinformación.")

print("\n💜 Gracias por jugar y aprender sobre el SOMP.")

